sudo modprobe -a tcp_bbr
sudo modprobe -a tcp_bic
sudo modprobe -a tcp_cdg
sudo modprobe -a tcp_dctcp
sudo modprobe -a tcp_highspeed
sudo modprobe -a tcp_htcp
sudo modprobe -a tcp_hybla
sudo modprobe -a tcp_illinois
sudo modprobe -a tcp_lp
sudo modprobe -a tcp_nv
sudo modprobe -a tcp_scalable
sudo modprobe -a tcp_vegas
sudo modprobe -a tcp_veno
sudo modprobe -a tcp_westwood
sudo modprobe -a tcp_yeah
sudo sysctl -w net.ipv4.ip_forward=1
sudo sysctl -w net.ipv4.ip_forward=1
