from abc import ABC, abstractmethod
import numpy as np

class Scoring(ABC):
    """
    Abstract base class defining the interfaces
    for computing score of a trace from performance
    logs generated by the execution module.
    """

    def compute_relative_difference(self, reference_score, target_score, score_type):
        """
        Computes score of the trace by taking the relative difference
        of reference_score and target_score.

        Parameters:
        float, float, int: The scores of the reference and target.
        Parameter score_type defines whether a higher score is better or
        a lower one is better.

        Returns:
        float: Returns the relative difference of the two inputs
        """

        if score_type == 1: #higher is better
            if reference_score == 0:
                return -100
            else:
                return (reference_score - target_score) / reference_score
        elif score_type == 2: #lower is better
            if target_score == 0:
                return -100
            else:
                return (target_score - reference_score) / target_score
    
    def __compute_score_of_a_protocol_from_logs(self, log_files):
        """
        Computes score of reference or target based on the
        log files generated by the execution module.

        Parameters:
        log_files[list]: list of files to compute the score

        Returns:
        float: the score of reference or target
        """
        pass

class SingleCCProtocolScore():
    def __init__(self, wt=0.5, wl=0.5):
        self.wt = wt
        self.wl = wl
    def tbd(self, throughput, latency):
        return throughput / latency
    def w_sum(self, throughput, latency, t_ref, l_ref):
        t_rel = throughput / t_ref
        l_rel = l_ref / latency
        return self.wt * t_rel + self.wl * l_rel
    def g_mean_sum(self, throughput, latency, t_ref, l_ref):
        t_rel = throughput / t_ref
        l_rel = l_ref / latency
        return (t_rel ** self.wt) * (l_rel ** self.wl)

def compute_score(ref_scores, tar_scores):
    ref_score = np.median(ref_scores)
    tar_score = np.median(tar_scores)

    return (ref_score - tar_score) / ref_score